# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
      - master
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: 'hellomy-house/intelior'
          ref: ${{ github.head_ref }}
          persist-credentials: false

      # Runs a single command using the runners shell
      - name: npm install
        run: |
          npm install

      # Runs a single command using the runners shell
      - name: build
        run: |
          npx gatsby build --prefix-paths

      # Runs a single command using the runners shell
      - name: deploy 
        run: |
          mkdir ~/.git
          git config --global user.email "dev@hellomy.house" & git config --global user.name "hellomy-house"
          npx gh-pages -d public -b gh-pages -r https://github.com/hellomy-house/intelior.git
